name: Fluent Docker release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
  push:
    branches:
      - fluent
    tags:
      - fluent-v*.*.*

env:
  CARGO_TERM_COLOR: always
  DOCKER_IMAGE_NAME: ghcr.io/fluentlabs-xyz/rundler

jobs:
  build:
    name: build and push
    if: github.repository == 'fluentlabs-xyz/rundler'
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@1.85.0
        with:
          components: clippy

      - name: Install toolchain (nightly)
        run: rustup toolchain add nightly --component rustfmt --profile minimal

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - uses: taiki-e/install-action@cross

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker builder
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install arm64,amd64
          docker buildx create --use --name cross-builder

      - name: Build and push image
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            sudo -E env "PATH=$PATH" DOCKER_IMAGE_NAME="${DOCKER_IMAGE_NAME}" make GIT_TAG="${{ github.event.inputs.version }}" docker-build 
          elif [[ "${{ github.ref_name }}" =~ ^fluent-v(\d+)\.(\d+)\.(\d+)$ ]]; then
            sudo -E env "PATH=$PATH" DOCKER_IMAGE_NAME="${DOCKER_IMAGE_NAME}" make docker-build-latest
          else 
            sudo -E env "PATH=$PATH" DOCKER_IMAGE_NAME="${DOCKER_IMAGE_NAME}" make GIT_TAG="${{ github.ref_name }}" docker-build 
          fi
